### PR TITLE
feat: do not spawn pouchdb server

### PR DESCRIPTION
**Pull request by jo**
This is done in kazana-server now.

Depends on https://github.com/eHealthAfrica/kazana-server/pull/49

### CODE REVIEW

**Comment by patriciagarcia** [comment]
Blocked by https://github.com/eHealthAfrica/kazana-server/pull/49

**Comment by gr2m** [comment]
I'd release a new major verion for that

**Comment by jo** [comment]
why? Its just internal restructuring plus a new feature. It should not break anything, or am I missing something?

**Comment by gr2m** [comment]
naaaah you are right, it's just the pre– :coffee: me :)

**Pull request merged**
