### PR TITLE
chore: add kazana raw data version without attachment data

### PR DESCRIPTION
**Pull request by lucidNTR**
BREAKING: this removes the attachment base64 data from the result of submitting to raw data

### CODE REVIEW

**Comment by jo** [comment]
LGTM if the tests pass.

**Comment by jo** [comment]
You were faster: https://github.com/eHealthAfrica/kazana/pull/204

**Comment by jo** [comment]
than the bot

**Comment by lucidNTR** [comment]
ahh greenkeeper :-D

**Comment by lucidNTR** [comment]
merge? @jo

**Comment by jo** [comment]
Sure, the tests are so green they can't more green.

**Pull request merged**
